name: flutter_flask_login
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.5
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0


flutter:

  uses-material-design: true