name: flutter_flask_login
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 0.4.3
  http: 0.12.0
  get_it: 5.0.6
  flutter_bloc: 6.1.3
  dio: ^3.0.10
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.1+1
  json_serializable: 3.5.1


flutter:

  uses-material-design: true